language: java
# use Java 8
jdk:
- oraclejdk8

# set the X11 Display variable as a global environment variable
env:
  global:
    - DISPLAY=:99
# start xvfb using the the DISPLAY port
before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- $DISPLAY -ac -screen 0 1280x1024x24"
  - sleep 3
before_install: sudo apt-get install xvfb

# we need a few extra packages to be installed
# 1. for Java FX support the latest oracle-java8 needs to be installed
# 2. xvfb is needed to run GUI tests and avoid headless mode
addons:
  apt:
    packages:
      - oracle-java8-installer
      - xvfb

sudo: true

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

# Build the server first and then build the eclipse plug-ins
script: 
- ./mvnw clean verify

# integration with codecov
after_success:
- bash <(curl -s https://codecov.io/bash)
