language: java
# use Java 8
jdk:
- oraclejdk8

# To be able to run ui test also start xvfb
services:
  - xvfb

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

# Build the server first and then build the eclipse plug-ins
script: 
- ./mvnw clean verify

# integration with codecov
after_success:
- bash <(curl -s https://codecov.io/bash)
